[tool.black]
line-length = 120
target-version = ["py36", "py37", "py38", "py39", "py310"]
extend-exclude = "robosuite_models/((robots/assets))"

[tool.isort]
profile = "black"
line_length = 120
skip = ["__init__.py"]
filter_files = true
py_version = "all"
extend_skip = [
    "robosuite_models/assets"
    ]
